# Labels PRs based on which files changed
# Docs: https://github.com/actions/labeler

documentation:
  - changed-files:
    - any-glob-to-any-file: ["**/*.md", "docs/**"]

dependencies:
  - changed-files:
    - any-glob-to-any-file: ["package.json", "package-lock.json"]

tests:
  - changed-files:
    - any-glob-to-any-file: "test/**"

source:
  - changed-files:
    - any-glob-to-any-file: "src/**"

ci:
  - changed-files:
    - any-glob-to-any-file: ".github/**"
